basePath: /v1
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API12222
  version: "1.0"
paths:
  /api/users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"RetCode":0,"UserInfo":{},"Action":"GetAllUserResponse"}'
          schema:
            type: string
      summary: 获取所有用户
  /api/users/{name}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"RetCode":0,"UserInfo":{},"Action":"GetOneUserResponse"}'
          schema:
            type: string
      summary: 获取单个用户
swagger: "2.0"
