# This is the config file for go site demo project.
title = "go site config file"

[Database]
    DbConn = "root:hillstone!1@tcp(192.168.226.128:3306)/flask?charset=utf8"
    MaxOpenConn = 100
    MaxIdleConn = 100
    MaxLifetime = 3600


[Server]
    Host = "127.0.0.1"
    Port = 5000


[Servers]
    ip = "127.0.0.1"
    port = 5000

[Log]
    LogLevel="debug"
    LogPath = "./logs"
    LogSize =  500
    LogName = "go-site.log"
    LogAge = 7 #day


